name: Build
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build-python:
    uses: goes-funky/workflows/.github/workflows/build-python.yaml@master
    with:
      python-version: "3.9"
      skip-mypy: true
      skip-tests: false
      skip-isort: true
      skip-format: true
      skip-lint: true
#    secrets:
#      codecov-token: ${{ secrets.CODECOV_TOKEN }}